//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using UnityEngine;
using Frameworks;

namespace Frameworks
{
    public sealed class Global
    {
        public const byte   PLAYER_NAME_SIZE          = 32;
        public const byte   CONTENT_DEC_SIZE          = 128;
        public const byte   ACCOUNT_NAME_SIZE         = 32;
        public const byte   ZONE_NAME_SIZE            = 32;               //大区名字Size
        public const byte   PASSWORD_SIZE             = 32;
        public const byte   PLAYER_SIGN_SIZE          = 32;               //
        public const byte   EMAIL_SIZE                = 64;               //
        public const byte   MAX_MONSTER_COUNT         = 6;                //怪物组最大怪物数量
        public const byte   MAX_FIGHT_POS_COUNT       = 6;                //最大出战位置数
        public const byte   MAX_FIGHT_COUNT           = 6;                //最大出战人数
        public const byte   MAX_BATTLE_COUNT          = 12;               //战斗最大人数
        public const byte   MAX_SKILL_COUNT           = 7;                //最大被动技能数量
        public const byte   MAX_BUFF_COUNT            = 6;                //战斗中最多叠加的Buf数量
        public const ushort MAX_BATTLE_ROUND          = 30;               //战斗中最大时间

        public const byte   MAX_SKILL_UNLOCK_COUNT    = 3;                //主动技能解锁数量
        public const byte   MAX_PSKILL_UNLOCK_COUNT   = 4;                //被动技能解锁数量
        public const byte   MAX_COMBO_SKILL           = 5;                //最大的组合技能数量
        public const byte   DEFAULT_MONSTER_FORMATION = 1;                //默认怪物组阵法
        public const float  DEFAULT_ASPECT_RATIO      = 960F / 640;
        public const float  DEFAULT_XY_ASPECT_RATIO   = 640F / 960;
        public const byte   LOGIN_ZONE_COUNT          = 5;                //登录服务器列表数量
        public const int    CARD_RANK_MAX             = 7;
        public const byte   MAX_VIP_LEVEL             = 12;               //最大VIP等级
        public const int    INV_EX_COST               = 50;               //扩充背包花费
        public const int    CARDBGUP_LIMITE           = 300;              //抽卡时card拍数量上限
        public const int    INV_EX_COUNT              = 5;                //扩充背包收益
        /// <summary>
        /// 最大月份
        /// </summary>
        public const byte   MAX_MONTH                 = 12;
        /// <summary>
        /// 累计的五个奖励数组
        /// </summary>
        public const byte SIGN_REWARD_COUNT           = 5;
        public static Vector2 ScreenSize;

#if UNITY_EDITOR
        public static readonly string LOCAL_RES_URL = "file://" + Application.dataPath + "/Cache/";
        public static readonly string LOCAL_RES_DIR = Application.dataPath + "/Cache";
#elif UNITY_IPHONE || UNITY_ANDROID || UNITY_STANDALONE_WIN
        public static readonly string LOCAL_RES_URL = "file://" + Application.persistentDataPath + "/Cache/";
        public static readonly string LOCAL_RES_DIR = Application.persistentDataPath + "/Cache";

#endif

        public static void InitScreenSize()
        {
             ScreenSize = new Vector2(Screen.width, Screen.height);
        }
    }
}

